/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tampilan;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author angga murdika
 */
public class form_SO extends javax.swing.JFrame {

    /**
     * Creates new form form_barang
     */
    public form_SO() {
        initComponents();
        txtKeterangan.putClientProperty("JTextField.placeholderText", "Masukkan Keterangan");
        txtTanggal.putClientProperty("JTextField.placeholderText", "Tanggal");


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        lbTab = new javax.swing.JLabel();
        lbKodeBarang = new javax.swing.JLabel();
        lbKeterangan = new javax.swing.JLabel();
        lbStokFisik = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        ddKodeBarang = new javax.swing.JComboBox<>();
        sStokFisik = new javax.swing.JSpinner();
        txtKeterangan = new javax.swing.JTextField();
        lbTanggal = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTab.setFont(new java.awt.Font("SF Pro Text", 1, 24)); // NOI18N
        lbTab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTab.setText("Stock Opname");
        lbTab.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbKodeBarang.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        lbKodeBarang.setText("Kode Barang");

        lbKeterangan.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        lbKeterangan.setText("Keterangan");

        lbStokFisik.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        lbStokFisik.setText("Stok Fisik");

        btnSimpan.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        btnSimpan.setText("Simpan");

        ddKodeBarang.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        ddKodeBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode Barang", "Item 2", "Item 3", "Item 4" }));
        ddKodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddKodeBarangActionPerformed(evt);
            }
        });

        sStokFisik.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        sStokFisik.setAlignmentX(0.0F);
        sStokFisik.setAlignmentY(0.0F);

        txtKeterangan.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        txtKeterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeteranganActionPerformed(evt);
            }
        });

        lbTanggal.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        lbTanggal.setText("Tanggal");

        txtTanggal.setEditable(false);
        txtTanggal.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        txtTanggal.setForeground(new java.awt.Color(153, 153, 153));
        txtTanggal.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbTanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbKodeBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ddKodeBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbStokFisik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sStokFisik, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSimpan)
                        .addComponent(lbTab, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                        .addComponent(lbKeterangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtKeterangan)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lbTab)
                .addGap(18, 18, 18)
                .addComponent(lbTanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbKodeBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ddKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbStokFisik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sStokFisik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbKeterangan)
                .addGap(5, 5, 5)
                .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnSimpan)
                .addGap(53, 53, 53))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ddKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddKodeBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddKodeBarangActionPerformed

    private void txtKeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeteranganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_SO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> ddKodeBarang;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel lbKeterangan;
    private javax.swing.JLabel lbKodeBarang;
    private javax.swing.JLabel lbStokFisik;
    private javax.swing.JLabel lbTab;
    private javax.swing.JLabel lbTanggal;
    private javax.swing.JSpinner sStokFisik;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
